name: Construir imagen y subirla a DockerHub

on:
    push:
        branches: [ "main" ]
    pull_request:
            branches: [ "main" ]

jobs:

    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Login en Docker Hub
              uses: docker/Login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Preparar construcion en docker build
              uses: docker/setup-buildx-action@v2
            - name: Construir imagen y subirla a DockerHub
              uses: docker/setup-build-push-actions@v4
              with: 
                context: .
                file: ./Dockerfile
                push: true
                tags: |
                    ${{ secrets.DOCKERHUB_USERNAME }}/docker-github-actions:latets
                    ${{ secrets.DOCKERHUB_TOKEN }}/docker-github-actions:${{github.sha}}